name: lulu_stylist_app
description: A new Flutter app for Lulu Stylist by Persist Ventures
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_gemini: ^2.0.3
  dash_chat_2: ^0.0.20
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.4+1
  shared_preferences: ^2.3.2
  go_router: ^14.3.0
  flutter_screenutil: ^5.9.0
  loading_animation_widget: ^1.3.0
  widgetbook_annotation: ^3.2.0
  modal_bottom_sheet: ^3.0.0
  awesome_snackbar_content: ^0.1.3
  phone_form_field: ^9.2.8
  #  fluttertoast: ^8.2.8
  logger: ^2.4.0
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
  # awesome_notifications: ^0.9.2
  # awesome_notifications_fcm: ^0.9.2
  home_widget: ^0.7.0
  flutter_secure_storage: ^9.2.2
  dio_brotli_transformer: ^2.0.0
  dio_smart_retry: ^6.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  retrofit_generator: ^8.0.5
  pretty_dio_logger: ^1.3.1
  mqtt5_client: ^4.2.2
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.4
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  nanoid: ^1.0.0
  connectivity_plus: ^5.0.2
  # firebase_installations: ^16.3.6
  json_annotation: ^4.7.0
  #  workmanager: ^0.5.2
  firebase_in_app_messaging: ^0.7.5+7
  line_icons: ^2.0.3
  intl_phone_number_input: ^0.7.4
  lottie: ^3.1.3
  equatable: ^2.0.5
  path_provider: ^2.0.11
  path: ^1.8.2
  dartz: ^0.10.1
  http: ^1.2.2
  get_it: ^8.0.3
  chips_input: ^0.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.5
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/logo/lulu.svg
    - assets/lottie/login_lottie.json
    - assets/lottie/onboarding.json
    - assets/lottie/login_success.json
    - assets/lottie/profile_complete.json
    - assets/lottie/profile_update.json
    - assets/bottom_bar_icons/
    - assets/lottie/search_lottie.json
    - assets/bodytype.webp
    - assets/images/default.png

  uses-material-design: true
  generate: true

global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
